spring.application.name=notification-service
server.port=4089
spring.main.web-application-type=reactive

#======================Application Configuration===============================
#server.servlet.context-path=/api
application.title=Notification-Service
application.version=@project.version@
application.description=@project.description@

#============================== Config Server Configuration ======================
spring.cloud.config.uri=http://localhost:4088
spring.config.import=optional:configserver:http://localhost:4088

#======================Gmail Configuration/AWS Config later=======================================
app.host.email=no-reply@favourite.collections
app.host.name=Favourite Collections

#MAIL SETTINGS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=favourite-collections
spring.mail.password=qxgp mggu xlnb pfby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#======================Logging Configuration=======================================
logging.file.path=logs/
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.level.com.cdl.FineractServiceSimplified=debug
logging.level.root=INFO

#======================Eureka Configuration=======================================
eureka.client.serviceUrl.defaultZone=http://favourite:pa55word@localhost:4080/eureka
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.metadata-map.startup= ${random.int}
eureka.client.registry-fetch-interval-seconds= 5

#======================Actuator Configuration=======================================
management.info.env.enabled=true
info.app.name=Notification Service Actuator
info.app.java.version=1
info.app.type=Notification Service
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.jms.enabled=false
info.tags.environment=test
management.server.base-path=/
management.endpoint.logfile.enabled=true
eureka.instance.secure-port-enabled=false
eureka.instance.non-secure-port-enabled=true
management.endpoint.health.timeout=30s
Server.ssl.enabled=false

spring.codec.max-in-memory-size=20MB

# Set logging level for your application
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.server=DEBUG

#======================RabbitMQ Configuration=======================================
#RABBITMQ SETTINGS
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:some_password}

#=============================
# JPA CREDENTIALS
#=============================
#DATABASE SETTINGS
spring.datasource.url=jdbc:postgresql://localhost:5432/favourite_collections
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=favourite_admin
spring.datasource.password=allForOne
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.format_sql=true

#SWAGGER UI CONFIGURATION
# swagger-ui custom path http://localhost:4082/swagger-ui.html
springdoc.api-docs.groups.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.check-template-location=true
