#======================================= App Configuration =======================================
spring.application.name=api-gateway
server.port=4081
spring.thymeleaf.check-template-location=false
spring.profiles.active=local
#server.servlet.context-path=/api
