#======================================= App Configuration =======================================
spring.application.name=api-gateway
server.port=4081
spring.thymeleaf.check-template-location=false
spring.profiles.active=local
#server.servlet.context-path=/api

favourite.openapi.dev-url=http://localhost:4082
favourite.openapi.prod-url=https://www.favorite-collections.ng:4082

# Spring boot admin server
#spring.boot.admin.client.url=http://localhost:4083

application.title=Api-Gateway
application.version=@project.version@
application.description=@project.description@

#======================Logging Configuration=======================================
logging.file.path=logs/
logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.max-file-size=10MB

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=INFO

#======================Actuator Configuration=======================================
management.info.env.enabled=true
info.app.name=Api-Gateway Actuator
info.app.java.version=1.0
info.app.type=Api-Gateway MicroService
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#======================Eureka Configuration=======================================
eureka.client.serviceUrl.defaultZone=http://favourite:pa55word@localhost:4080/eureka

#Routes Discovery Automatically
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

## http vs lb (load balancer)
## use http when it is one service and use lb when you have multiple same service deployed

## Discovery Service Route
eureka.port=4080
# Access Via http://localhost:4080/eureka/web
spring.cloud.gateway.routes[0].id=discovery-service
spring.cloud.gateway.routes[0].uri=http://localhost:${eureka.port}
spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka/**
spring.cloud.gateway.routes[0].filters[0]=SetPath=/

## Discover Service Static Resources Route
spring.cloud.gateway.routes[1].id=discovery-service-static
spring.cloud.gateway.routes[1].uri=http://localhost:${eureka.port}
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/**

#====================== Swagger =======================================
#http://localhost:4081/swagger-ui.html
#http://localhost:4081/webjars/swagger-ui/index.html

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs

springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[0].name=Api-Gateway
springdoc.swagger-ui.urls[0].primaryName=Api-Gateway

springdoc.swagger-ui.urls[1].url=/core/api/v3/api-docs
springdoc.swagger-ui.urls[1].name=Core-Service
springdoc.swagger-ui.urls[1].primaryName=Core-Service

#springdoc.swagger-ui.urls[2].url=/notification/api/v3/api-docs
#springdoc.swagger-ui.urls[2].name=Notification-Service
#springdoc.swagger-ui.urls[2].primaryName=Notification-Service


##======================Cors Origin=======================================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600
spring.cloud.gateway.globalcors.corsConfigurations.[/**].exposedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=false

#==============SSL Production-#SSL Key Info=======================================

#security.require-ssl=true
#server.ssl.key-store-password=@1234
#server.ssl.key-store=classpath:creditdirectngwild.pfx
#server.ssl.key-store-type=PKCS12
