#======================================= App Configuration =======================================
server.port=4081
spring.application.name=api-gateway
spring.main.web-application-type=reactive
#spring.profiles.active=dev

#=======================================App Details=======================================
application.title=Api Gateway
application.version=@project.version@
application.description=@project.description@
favourite.base.path=/api/v1
favourite.openapi.dev-url=http://localhost:4082
favourite.openapi.prod-url=https://www.favorite-collections.ng:4082

#============================== Config Server Configuration ======================
spring.cloud.config.uri=http://localhost:4088
spring.config.import=optional:configserver:http://localhost:4088

#======================JWT Secret Key Configuration==============================
app.jwt.secret.key=T3ZlcnZpZXcKR3JlZXRpbmdzISDwn5GL8J+PvgoKV2VsY29tZSB0byB0aGUgY2VudHJhbCBodWIgZm9yIGluZm9ybWF0aW9uIHJlZ2FyZGluZyBvdXIgVmFsdWUtQWRkZWQgU2VydmljZSAoVkFTKSBwbGF0Zm9ybS4KClRoaXMgaXMgdGhlIG9mZmljaWFsIFZBUyBQcm9kdWN0IFdpa2ksIHlvdXIgb25lLXN0b3AgZGVzdGluYXRpb24gZm9yIGNvbXByZWhlbnNpdmUgaW5zaWdodHMgaW50byBvdXIgVmFsdWUtQWRkZWQgU2VydmljZSBwbGF0Zm9ybS4gSGVyZSwgeW91J2xsIGZpbmQgYSB0cmVhc3VyZSB0cm92ZSBvZiByZXNvdXJjZXMgY2FyZWZ1bGx5IGN1cmF0ZWQgdG8gZW5oYW5jZSB5b3VyIHVuZGVyc3RhbmRpbmcgYW5kIHV0aWxpemF0aW9uIG9mIG91ciBWQVMgc29sdXRpb24uCgpEaXNjb3ZlciBhIHBsZXRob3JhIG9mIHJlc291cmNlcyBpbmNsdWRpbmc6CgpBcmNoaXRlY3R1cmUgZGlhZ3JhbXMgZWx1Y2lkYXRpbmcgdGhlIGludHJpY2F0ZSBmcmFtZXdvcmsgb2Ygb3VyIFZBUyBwbGF0Zm9ybS4KUHJvY2VzcyBmbG93IGRpYWdyYW1zIGRlbGluZWF0aW5nIHRoZSBzZWFtbGVzcyBmbG93IG9mIGludGVyYWN0aW9ucyBhbmQgc2VydmljZXMgd2l0aGluIG91ciBzeXN0ZW0uClRlc3QgcmVwb3J0cyBzaG93Y2FzaW5nIHRoZSByaWdvcm91cyB0ZXN0aW5nIHByb2NlZHVyZXMgdW5kZXJ0YWtlbiB0byBlbnN1cmUgdGhlIHJlbGlhYmlsaXR5IGFuZCBzZWN1cml0eSBvZiBvdXIgVkFTIHBsYXRmb3JtLgpEZXBsb3ltZW50IG5vdGVzIG9mZmVyaW5nIHZhbHVhYmxlIGluc2lnaHRzIGFuZCBndWlkZWxpbmVzIGZvciBkZXBsb3lpbmcgb3VyIFZBUyBwbGF0Zm9ybSBhY3Jvc3MgdmFyaW91cyBlbnZpcm9ubWVudHMuClByb2R1Y3QgUmVxdWlyZW1lbnQgRG9jdW1lbnRzIChQUkRzKSBvdXRsaW5pbmcgdGhlIGZlYXR1cmVzLCBmdW5jdGlvbmFsaXRpZXMsIGFuZCBzcGVjaWZpY2F0aW9ucyBvZiBvdXIgVkFTIHBsYXRmb3JtLgpDb21wcmVoZW5zaXZlIGRvY3VtZW50YXRpb24gZnVybmlzaGluZyBkZXRhaWxlZCBpbnN0cnVjdGlvbnMgYW5kIGV4cGxhbmF0aW9ucyB0byBzdHJlYW1saW5lIHRoZSBpbnRlZ3JhdGlvbiBhbmQgb3BlcmF0aW9uIG9mIG91ciBWQVMgcGxhdGZvcm0gd2l0aGluIHlvdXIgc3lzdGVtcy4KV2hldGhlciB5b3UncmUgYSBkZXZlbG9wZXIsIGluZnJhc3RydWN0dXJlIGVuZ2luZWVyLCBwcm9kdWN0IGFuYWx5c3QsIG9yIGJ1c2luZXNzIHN0YWtlaG9sZGVyLCB0aGlzIFdpa2kgc2VydmVzIGFzIHlvdXIgdWx0aW1hdGUgcmVzb3VyY2UgaHViIGZvciBhbGwgdGhpbmdzIHJlbGF0ZWQgdG8gb3VyIFZhbHVlLUFkZGVkIFNlcnZpY2UgcGxhdGZvcm0uCgpEZWx2ZSBpbnRvIHRoZSB3ZWFsdGggb2Yga25vd2xlZGdlIGFuZCBlcXVpcCB5b3Vyc2VsZiB3aXRoIHRoZSBuZWNlc3NhcnkgdG9vbHMgdG8gbWF4aW1pemUgdGhlIHBvdGVudGlhbCBvZiBvdXIgVkFTIHBsYXRmb3JtIGVmZmVjdGl2ZWx5Lg==

#======================Logging Configuration=======================================
logging.file.path=logs/
logging.file.name=logs/application.log
logging.logback.rollingpolicy.max-file-size=10MB

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

#======================Actuator Configuration=======================================
management.info.env.enabled=true
info.app.name=Api Gateway Actuator
info.app.java.version=1
info.app.type=Api Gateway
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.jms.enabled=false
management.endpoint.logfile.enabled=true
info.tags.environment=test
eureka.instance.non-secure-port-enabled=true
#spring.boot.admin.client.instance.metadata.managementUrl=http://localhost:${server.port}/actuator

#======================Eureka Configuration======================================
eureka.port=4080
eureka.client.serviceUrl.defaultZone=http://favourite:pa55word@localhost:${eureka.port}/eureka
eureka.instance.secure-port-enabled=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.metadata-map.startup= ${random.int}
eureka.client.registry-fetch-interval-seconds=5

#Routes Discovery Automatically
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
## http vs lb (load balancer)
## Discovery Service Route
# Access Via http://localhost:2024/eureka/web
spring.cloud.gateway.routes[0].id=api-gateway
spring.cloud.gateway.routes[0].uri=http://localhost:2020
spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[0].filters[0]=SetPath=/

## Discover Service Static Resources Route
spring.cloud.gateway.routes[1].id=api-gateway-static
spring.cloud.gateway.routes[1].uri=http://localhost:2020
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/**

spring.cloud.gateway.routes[2].id=api-gateway
spring.cloud.gateway.routes[2].uri=lb://api-gateway
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.routes[2].predicates[1]=Path=/v3/api-docs/api-gateway

spring.cloud.gateway.routes[3].id=core-service
spring.cloud.gateway.routes[3].uri=lb://core-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/core-service/**
spring.cloud.gateway.routes[3].predicates[1]=Path=/core-service/v3/api-docs

spring.cloud.gateway.routes[4].id=core-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/notification-service/**
spring.cloud.gateway.routes[4].predicates[1]=Path=/notification-service/v3/api-docs

#====================== Swagger =======================================
#http://localhost:2019/swagger-ui.html
#http://localhost:2019/webjars/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs

springdoc.swagger-ui.urls[0].url=/v3/api-docs
springdoc.swagger-ui.urls[0].name=Api Gateway
springdoc.swagger-ui.urls[0].primaryName=Api Gateway

springdoc.swagger-ui.urls[1].url=/core-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Core-Service
springdoc.swagger-ui.urls[1].primaryName=Core-Service

springdoc.swagger-ui.urls[2].url=/notification-service/v3/api-docs
springdoc.swagger-ui.urls[2].name=Notification-Service
springdoc.swagger-ui.urls[2].primaryName=Notification-Service

#DATABASE SETTINGS
spring.datasource.url=jdbc:postgresql://localhost:5432/favourite_collections
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=favourite_admin
spring.datasource.password=allForOne
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.format_sql=true

##======================Cors Origin=======================================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600
spring.cloud.gateway.globalcors.corsConfigurations.[/**].exposedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=false

spring.main.allow-bean-definition-overriding=true
