
# Application
spring.application.name=core-service
server.port=4082
spring.profiles.active=local

#server.servlet.context-path=/api
application.title=Core-Service
application.version=@project.version@
application.description=@project.description@

favourite.base.path=/api/v1
favourite.openapi.dev-url=http://localhost:4082
favourite.openapi.prod-url=https://www.favorite-collections.ng:4082

management.health.mail.enabled=false